version: 2.1
orbs:
  maven: circleci/maven@0.0.12
jobs:
   build:
    docker:
      - image: circleci/openjdk:9-jdk
    working_directory: ~/circle-ci-test-project
    steps:
      - checkout
      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: circle-ci-test-project-{{ checksum “pom.xml” }}
      - run: mvn dependency:go-offline # gets the project dependencies
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: circle-ci-test-project-{{ checksum “pom.xml” }}
      - run: mvn clean install # run the actual tests
      
       - store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard. 
      # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: target/surefire-reports
      
      - store_artifacts: # store the uberjar as an artifact
      # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: target/circle-ci-test-project-0.0.1-SNAPSHOT.jar
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples    

workflows:
  maven_test:
    jobs:
      - build
